download just binary
build just dynamic binary
build server
build benchmarks
build test

run benchmarks
run tests

https://redis.io/commands/lpop
https://itnext.io/benchmarking-the-experimental-redis-multi-threaded-i-o-1bb28b69a314
do this benchmark and a comparison against redis

JavaScript - the REDIS slayer

